package com.wafman.taskmaster.taskmaster.Model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.UUID;

@DynamoDBTable(tableName = "TaskMaster")
public class Task {
    //instance variables
    private UUID id;
    private String title;
    private String description;
    private String assignee;
    private String status;
    private String pic;

    //constructors
    public Task(){}

    public Task(String pic){
        this.pic = pic;
    }

    public Task(String title, String description, String pic){
        this.title = title;
        this.description = description;
        this.status = "Available";
        this.pic = pic;
    }

    public Task(String title, String description, String assignee, String pic){
        this.title = title;
        this.description = description;
        this.assignee = assignee;
        this.status = "Assigned";
        this.pic = pic;
    }


    //getters && setters

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }


    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDBAttribute
    public String getAssignee() {
        return assignee;
    }

    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    @DynamoDBAttribute
    public String getPic() {
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }
}
